# Generated by Django 4.1.7 on 2023-03-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogame_store', '0003_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(max_length=110),
        ),
        migrations.AlterField(
            model_name='loja',
            name='endereco',
            field=models.CharField(max_length=110),
        ),
    ]
